name: Generate contributor icons

on: 
  schedule:
    - cron: '0 12 * * *'

  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  generate-contributor-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        id: contributors
        with:
          filter-author: (renovate\[bot\]|renovate-bot|github-actions\[bot\]|dependabot\[bot\])
          hideName: 'false'
          avatarSize: 100
      - name: Modify htmlTable README.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          body: '${{steps.contributors.outputs.htmlTable}}'